### ISSUE TITLE
NameError: typo introduced in last commit

### ISSUE THREAD

**Issue by tdayris** [davidaknowles/leafcutter#102]
Hi, this is a typo introduced in the last commit :

```
Traceback (most recent call last):
  File "/home/tdayris/Documents/Developpement/rna-splicing-star-leafcutter/test/analysis/leafcutter//clustering/leafcutter_cluster.py", line 489, in <module>
    main(options, libl)
  File "/home/tdayris/Documents/Developpement/rna-splicing-star-leafcutter/test/analysis/leafcutter//clustering/leafcutter_cluster.py", line 12, in main
    refine_clusters(options)
  File "/home/tdayris/Documents/Developpement/rna-splicing-star-leafcutter/test/analysis/leafcutter//clustering/leafcutter_cluster.py", line 191, in refine_clusters
    minreads = nt(options.minreads)
NameError: global name 'nt' is not defined
```

Line 191 nt(...) → int(...)

**Comment by goldenflaw** [comment]
Thanks! Fixed now!

Best,
Yang

**Comment by tdayris** [comment]
Thanks!
