### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by ykohki** [davidaknowles/leafcutter#113]
Thank you for such a wonderful tool!

I have one error, when I do calculate intron clustering with clustering/leafcutter_cluster.py.

The error is 
```
 Traceback (most recent call last):
   File "/leafcutter/clustering/leafcutter_cluster.py", line 492, in <module>
     main(options, libl)
   File "/leafcutter/clustering/leafcutter_cluster.py", line 14, in main
     merge_junctions(options)
   File "/leafcutter/clustering/leafcutter_cluster.py", line 245, in merge_junctions
     for i in range(0,(len(lsts)/N)+1): 
 TypeError: 'float' object cannot be interpreted as an integer
```

My command is `python /clustering/leafcutter_cluster.py -j test_juncfiles.txt -m 50 -o testYRIvsEU -l 500000`.

When I check clustering/leafcutter_cluster.py,
```
 l.236 N = min([300, max([100, int(len(lsts)**(0.5))])])
 l.242 for i in range(0,(len(lsts)/N)+1): 
 l.243     lst = lsts[N*i:N*(i+1)]
```

I think this "N" may be invalid or "range" be invalid.
I'd be happy if you could give me some advice.

**Comment by jackhump** [comment]
leafcutter_cluster.py only works with python 2, are you using python 3 here? That could be the source of the error message.
