### ISSUE TITLE
SyntaxError in prepare_phenotype_table.py

### ISSUE THREAD

**Issue by jsonProgram** [davidaknowles/leafcutter#121]
python2.7 ./leafcutter/scripts/prepare_phenotype_table.py

Traceback (most recent call last):
  File "/data/jasonwu/02_bin/leafcutter/scripts/prepare_phenotype_table.py", line 5, in <module>
    import numpy as np
  File "/data/jasonwu/02_bin/miniconda3/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/data/jasonwu/02_bin/miniconda3/lib/python3.7/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/data/jasonwu/02_bin/miniconda3/lib/python3.7/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/data/jasonwu/02_bin/miniconda3/lib/python3.7/site-packages/numpy/core/overrides.py", line 182
    exec(source_object, scope)
SyntaxError: unqualified exec is not allowed in function 'decorator' it is a nested function

### 
/usr/bin/python2.7

hi, I am running this python script and come out this issue?
how can I figure it out ?

Thanks
J

**Comment by jsonProgram** [comment]
I  uninstall numpy and reinstall numpy, and fix this issue!
