### ISSUE TITLE
ValueError: need more than 6 values to unpack

### ISSUE THREAD

**Issue by geng-lee** [davidaknowles/leafcutter#171]
### Running leafcutter_cluster_regtools.py reports an error, how to solve this problem?

- ValueError: need more than 6 values to unpack

`Traceback (most recent call last):
  File "/backup/home/changxing/personal/LG/software/leafcutter/scripts/leafcutter_cluster_regtools.py", line 497, in <module>
    main(options, libl)
  File "/backup/home/changxing/personal/LG/software/leafcutter/scripts/leafcutter_cluster_regtools.py", line 14, in main
    pool_junc_reads(libl, options)
  File "/backup/home/changxing/personal/LG/software/leafcutter/scripts/leafcutter_cluster_regtools.py", line 47, in pool_junc_reads
    chrom, A, B, dot, counts, strand, rA,rb, rgb, blockCount, blockSize, blockStarts = lnsplit
ValueError: need more than 6 values to unpack`

**Comment by jackhump** [comment]
Hi, this message occurs when you use input junction files not created by regtools. Regtools junction files should be in BED12 format with 12 columns.

**Comment by geng-lee** [comment]
### Thank you very much for your reply. The problem has been solved.😁
