### ISSUE TITLE
clustering 

### ISSUE THREAD

**Issue by afadda1** [davidaknowles/leafcutter#185]
I'm getting this error
Traceback (most recent call last):
  File "abeer_old_folder/leafcutter-master/clustering/leafcutter_cluster_regtools.py", line 534, in <module>
    main(options, libl)
  File "abeer_old_folder/leafcutter-master/clustering/leafcutter_cluster_regtools.py", line 14, in main
    pool_junc_reads(libl, options)
  File "abeer_old_folder/leafcutter-master/clustering/leafcutter_cluster_regtools.py", line 48, in pool_junc_reads
    chrom, A, B, dot, counts, strand, rA,rb, rgb, blockCount, blockSize, blockStarts = lnsplit
ValueError: need more than 6 values to unpack

I checked my junc files and they have only 6 columns.

**Comment by goldenflaw** [comment]
Please use regtools to process your bam files into junction files.

Best,
Yang

**Comment by afadda1** [comment]
thanks. but it used to work in the past. I'm using the old scripts form LeafCutter.
so I should have more than 6 columns in the junc files?

**Comment by goldenflaw** [comment]
Yes, it says in the script name, that the version is for regtools.

Best,
Yang
