### ISSUE TITLE
Errors in worked example

### ISSUE THREAD

**Issue by decortja** [davidaknowles/leafcutter#192]
Hey all,

I am trying to run Leafcutter in a conda environment with python 2.7.13 and R 3.4.1. I have installed devtools and successfully run `devtools::install_github("davidaknowles/leafcutter/leafcutter")` for the requisite R packages. I have cloned the leafcutter github resources into my directory.

I am having two issues implementing the worked example in LeafCutter. When I run python_wrappers.sh, it runs fine until two errors abort the run:
1.	 A 404 error gets thrown when it tries to access the URL for `gencode.v19.annotation.gtf.gz` (see error message below). I tried to use the `download_human_annotations.sh` workaround suggested in another issue, but it still aborts with errors as it tries to decompress a `.gz` file that is nonexistent. I rebuilding LeafCutter from scratch to no avail, still no annotations gz file... Any corrections/workarounds for my attempt?

```
--2021-08-01 23:08:56--  https://web.stanford.edu/~dak33/leafcutter/**gencode.v19.annotation.gtf.gz**
Resolving web.stanford.edu (web.stanford.edu)... 171.67.215.200, 2607:f6d0:0:925a::ab43:d7c8
Connecting to web.stanford.edu (web.stanford.edu)|171.67.215.200|:443... connected.
**HTTP request sent, awaiting response... 404 Not Found
2021-08-01 23:08:56 ERROR 404: Not Found.**
...........................
Running cmd: python ../clustering/get_cluster_gene.py gencode.v19.annotation.gtf.gz tmpdir/leafcutter_perind.counts.gz
Traceback (most recent call last):
  File "../clustering/get_cluster_gene.py", line 37, in <module>
    ss2gene = get_feature(sys.argv[1], "exon")
  File "../clustering/get_cluster_gene.py", line 23, in get_feature
    F = gzip.open(fname)
  File "/[…….]/miniconda3/envs/leafcutter_env/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/[…….]/miniconda3/envs/leafcutter_env/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: 'gencode.v19.annotation.gtf.gz' 
```

2.	“leafcutter” in R did not download with the other R packages, so an error occurs in library(leafcutter). I have tried manually installing leafcutter with `install.packages(“leafcutter”)`, but I get the warning `package ‘leafcutter’ is not available`, regardless of what R version I have tried (I believe that’s 3.3.2, 3.4.1, 3.6, and 4.0.5 at this point). Any idea how to correctly install this package in R?

**Comment by goldenflaw** [comment]
Have you tried https://github.com/davidaknowles/leafcutter/issues/160 or https://github.com/davidaknowles/leafcutter/issues/188?
