### ISSUE TITLE
error in  prepare_phenotype_table.py

### ISSUE THREAD

**Issue by anneday** [davidaknowles/leafcutter#246]
I had a problem when using prepare_phenotype_table.py on the output of one bamfile.
It reported an error: 
Traceback (most recent call last):
  File "/home/gaoni/biosoft/leafcutter/scripts/prepare_phenotype_table.py", line 197, in <module>
    main(args[0], get_chromosomes(args[0]), get_blacklist_chromosomes(options.cbl), int(options.npcs) )
  File "/home/gaoni/biosoft/leafcutter/scripts/prepare_phenotype_table.py", line 142, in main
    for i in range(len(matrix[0,:])):
                       ~~~~~~^^^^^
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
This is my command:
 python /home/gaoni/biosoft/leafcutter/scripts/prepare_phenotype_table.py leafcutter_perind.counts.gz -p 5

This is part of my input:
chrom E100036200_L01_73_sorted.bam
chr1:829104:847654:clu_1_+ 52/152
chr1:829104:851927:clu_1_+ 34/152
chr1:847806:851927:clu_1_+ 66/152
chr1:852110:852671:clu_2_+ 50/121
chr1:852110:853391:clu_2_+ 37/121
chr1:852766:853391:clu_2_+ 34/121
chr1:853529:853726:clu_3_+ 63/137
chr1:853578:853726:clu_3_+ 41/137
chr1:853627:853726:clu_3_+ 33/137
chr1:2304102:2304293:clu_4_+ 129/211
chr1:2304108:2304293:clu_4_+ 82/211
chr1:2560714:2561494:clu_5_+ 42/213
chr1:2560714:2561673:clu_5_+ 171/213
chr1:5992788:6040517:clu_6_+ 31/189
chr1:6026445:6040517:clu_6_+ 158/189
chr1:6040645:6041831:clu_7_+ 52/329
chr1:6040645:6072755:clu_7_+ 201/329
chr1:6041872:6072755:clu_7_+ 76/329
chr1:6449091:6450444:clu_8_+ 267/619
chr1:6449091:6451603:clu_8_+ 94/619
chr1:6450470:6451603:clu_8_+ 258/619
chr1:6452096:6457184:clu_9_+ 400/498
chr1:6452096:6457187:clu_9_+ 98/498
I wonder if someone could help me about this?

**Comment by thomas-mazumder** [comment]
I just ran into this same error.
